/** @type {import('tailwindcss').Config} */
// Design tokens from CLONE_SPEC.md section 0.3 / 0.4 / 0.5.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    // 0.1 Breakpoints, mobile-first (phone is the base style)
    screens: { tablet: '810px', desktop: '1200px' },
    extend: {
      colors: {
        ink: '#262521',
        white: '#ffffff',
        paper: '#fdfcfb',
        'paper-80': '#fdfcfbcc',
        mist: '#f0f0ee',
        stone: '#f4f2f0',
        'ink-2': '#34332e',
        violet: '#a184fa',
        pink: '#f677fd',
        yellow: '#ffdd03',
        orange: '#f9720d',
        mint: '#63f6b5',
        'link-blue': '#678efd',
        red: '#ff2244',
        hairline: '#28262f1f',
        'line-5': 'rgba(38,37,33,0.05)',
        'logo-border': '#28262f0d',
        badge: 'rgba(246,246,246,0.12)',
        'faq-answer': 'rgba(38,37,33,0.8)',
        'caption-white': 'rgba(255,255,255,0.8)',
      },
      borderRadius: {
        avatar: '2px',
        media: '5px',
        card: '8px',
        panel: '12px',
        cookie: '14px',
        'panel-lg': '20px',
        badge: '29.53px',
      },
      fontFamily: {
        sans: ['"TWK Lausanne 400"', '"TWK Lausanne 400 Placeholder"', 'sans-serif'],
        'lausanne-bold': ['"TWK Lausanne 700"', '"TWK Lausanne 700 Placeholder"', 'sans-serif'],
        mono: ['"Geist Mono"', 'monospace'],
        inter: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'Helvetica', 'Arial', 'sans-serif'],
      },
      // 0.5 Type scale. Suffix -t = tablet, -p = phone.
      fontSize: {
        h1: ['64px', { lineHeight: '64px', letterSpacing: '-1.28px' }],
        'h1-t': ['51px', { lineHeight: '51px', letterSpacing: '-1.02px' }],
        'h1-p': ['34px', { lineHeight: '34px', letterSpacing: '-0.68px' }],
        // PAGES_SPEC 1.2 page-title H1 preset (8q1ft7), subpages only
        title: ['48px', { lineHeight: '48px', letterSpacing: '-0.96px' }],
        'title-t': ['38px', { lineHeight: '38px', letterSpacing: '-0.76px' }],
        'title-p': ['32px', { lineHeight: '32px', letterSpacing: '-0.64px' }],
        h3: ['40px', { lineHeight: '44px', letterSpacing: '-0.8px' }],
        'h3-t': ['32px', { lineHeight: '35.2px', letterSpacing: '-0.64px' }],
        'h3-p': ['26px', { lineHeight: '28.6px', letterSpacing: '-0.52px' }],
        h4: ['32px', { lineHeight: '35.2px', letterSpacing: '-0.64px' }],
        'h4-t': ['28px', { lineHeight: '30.8px', letterSpacing: '-0.56px' }],
        'h4-p': ['26px', { lineHeight: '28.6px', letterSpacing: '-0.52px' }],
        h5: ['24px', { lineHeight: '28.8px', letterSpacing: '-0.24px' }],
        'h5-t': ['20px', { lineHeight: '24px', letterSpacing: '-0.2px' }],
        h6: ['20px', { lineHeight: '22px', letterSpacing: '-0.4px' }],
        'h6-p': ['18px', { lineHeight: '19.8px', letterSpacing: '-0.36px' }],
        'body-l': ['16px', { lineHeight: '22.4px', letterSpacing: '0px' }],
        'body-s': ['14px', { lineHeight: '19.6px', letterSpacing: '0px' }],
        link: ['14px', { lineHeight: '18.2px', letterSpacing: '0px' }],
        button: ['16px', { lineHeight: '20.8px', letterSpacing: '0px' }],
        caption: ['12px', { lineHeight: '16.2px', letterSpacing: '-0.12px' }],
        mono: ['14px', { lineHeight: '16.8px', letterSpacing: '0.28px' }],
        'mono-s': ['12px', { lineHeight: '14.4px', letterSpacing: '0.24px' }],
        'faq-q': ['16px', { lineHeight: '22.4px', letterSpacing: '-0.16px' }],
        'faq-q-p': ['14px', { lineHeight: '19.6px', letterSpacing: '-0.14px' }],
        'faq-q-link': ['14px', { lineHeight: '18.2px', letterSpacing: '-0.14px' }],
        'faq-a': ['14px', { lineHeight: '19.6px', letterSpacing: '-0.14px' }],
      },
      boxShadow: {
        cookie: 'rgba(0,0,0,0.25) 0 2px 4px, inset 0 0 0 1px rgba(0,0,0,0.05)',
      },
      transitionTimingFunction: {
        framer: 'cubic-bezier(0.33, 1, 0.68, 1)',
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
  plugins: [],
}
